# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.1.0
maven_group=tnpl.immersiveenchanting

# Dependencies
fabric_api_version=0.152.1+26.2
strawberrylib_version=26.2-r1
enchancement_version=26.2-r1
midnightlib_version=1.9.3+26.2-fabric